package com.trinity.a20201031_marcregistre_nycschools.viewmodel;

public class MockResponseFileReader {

    public static String content = "[\n"
                  + "  {\n"
                  + "    \"dbn\": \"02M260\",\n"
                  + "    \"school_name\": \"Clinton School Writers & Artists, M.S. 260\",\n"
                  + "    \"boro\": \"M\",\n"
                  + "    \"overview_paragraph\": \"Students who are prepared for college must have an education that encourages them to take risks as they produce and perform. Our college preparatory curriculum develops writers and has built a tight-knit community. Our school develops students who can think analytically and write creatively. Our arts programming builds on our 25 years of experience in visual, performing arts and music on a middle school level. We partner with New Audience and the Whitney Museum as cultural partners. We are a International Baccalaureate (IB) candidate school that offers opportunities to take college courses at neighboring universities.\",\n"
                  + "    \"school_10th_seats\": \"1\",\n"
                  + "    \"academicopportunities1\": \"Free college courses at neighboring universities\",\n"
                  + "    \"academicopportunities2\": \"International Travel, Special Arts Programs, Music, Internships, College Mentoring English Language Learner Programs: English as a New Language\",\n"
                  + "    \"ell_programs\": \"English as a New Language\",\n"
                  + "    \"neighborhood\": \"Chelsea-Union Sq\",\n"
                  + "    \"building_code\": \"M868\",\n"
                  + "    \"location\": \"10 East 15th Street, Manhattan NY 10003 (40.736526, -73.992727)\",\n"
                  + "    \"phone_number\": \"212-524-4360\",\n"
                  + "    \"fax_number\": \"212-524-4365\",\n"
                  + "    \"school_email\": \"admissions@theclintonschool.net\",\n"
                  + "    \"website\": \"www.theclintonschool.net\",\n"
                  + "    \"subway\": \"1, 2, 3, F, M to 14th St - 6th Ave; 4, 5, L, Q to 14th St-Union Square; 6, N, R to 23rd St\",\n"
                  + "    \"bus\": \"BM1, BM2, BM3, BM4, BxM10, BxM6, BxM7, BxM8, BxM9, M1, M101, M102, M103, M14A, M14D, M15, M15-SBS, M2, M20, M23, M3, M5, M7, M8, QM21, X1, X10, X10B, X12, X14, X17, X2, X27, X28, X37, X38, X42, X5, X63, X64, X68, X7, X9\",\n"
                  + "    \"grades2018\": \"6-11\",\n"
                  + "    \"finalgrades\": \"6-12\",\n"
                  + "    \"total_students\": \"376\",\n"
                  + "    \"extracurricular_activities\": \"CUNY College Now, Technology, Model UN, Student Government, School Leadership Team, Music, School Musical, National Honor Society, The Clinton Post (School Newspaper), Clinton Soup (Literary Magazine), GLSEN, Glee\",\n"
                  + "    \"school_sports\": \"Cross Country, Track and Field, Soccer, Flag Football, Basketball\",\n"
                  + "    \"attendance_rate\": \"0.970000029\",\n"
                  + "    \"pct_stu_enough_variety\": \"0.899999976\",\n"
                  + "    \"pct_stu_safe\": \"0.970000029\",\n"
                  + "    \"school_accessibility_description\": \"1\",\n"
                  + "    \"directions1\": \"See theclintonschool.net for more information.\",\n"
                  + "    \"requirement1_1\": \"Course Grades: English (87-100), Math (83-100), Social Studies (90-100), Science (88-100)\",\n"
                  + "    \"requirement2_1\": \"Standardized Test Scores: English Language Arts (2.8-4.5), Math (2.8-4.5)\",\n"
                  + "    \"requirement3_1\": \"Attendance and Punctuality\",\n"
                  + "    \"requirement4_1\": \"Writing Exercise\",\n"
                  + "    \"requirement5_1\": \"Group Interview (On-Site)\",\n"
                  + "    \"offer_rate1\": \"Â—57% of offers went to this group\",\n"
                  + "    \"program1\": \"M.S. 260 Clinton School Writers & Artists\",\n"
                  + "    \"code1\": \"M64A\",\n"
                  + "    \"interest1\": \"Humanities & Interdisciplinary\",\n"
                  + "    \"method1\": \"Screened\",\n"
                  + "    \"seats9ge1\": \"80\",\n"
                  + "    \"grade9gefilledflag1\": \"Y\",\n"
                  + "    \"grade9geapplicants1\": \"1515\",\n"
                  + "    \"seats9swd1\": \"16\",\n"
                  + "    \"grade9swdfilledflag1\": \"Y\",\n"
                  + "    \"grade9swdapplicants1\": \"138\",\n"
                  + "    \"seats101\": \"YesÂ–9\",\n"
                  + "    \"admissionspriority11\": \"Priority to continuing 8th graders\",\n"
                  + "    \"admissionspriority21\": \"Then to Manhattan students or residents\",\n"
                  + "    \"admissionspriority31\": \"Then to New York City residents\",\n"
                  + "    \"grade9geapplicantsperseat1\": \"19\",\n"
                  + "    \"grade9swdapplicantsperseat1\": \"9\",\n"
                  + "    \"primary_address_line_1\": \"10 East 15th Street\",\n"
                  + "    \"city\": \"Manhattan\",\n"
                  + "    \"zip\": \"10003\",\n"
                  + "    \"state_code\": \"NY\",\n"
                  + "    \"latitude\": \"40.73653\",\n"
                  + "    \"longitude\": \"-73.9927\",\n"
                  + "    \"community_board\": \"5\",\n"
                  + "    \"council_district\": \"2\",\n"
                  + "    \"census_tract\": \"52\",\n"
                  + "    \"bin\": \"1089902\",\n"
                  + "    \"bbl\": \"1008420034\",\n"
                  + "    \"nta\": \"Hudson Yards-Chelsea-Flatiron-Union Square                                 \",\n"
                  + "    \"borough\": \"MANHATTAN\"\n"
                  + "  }\n"
                  + "]";
    }

